const PRESENCE_LINES = [
  // MewBit / catgirl / neon core
  "neon frequencies • /play",
  "vibe locked • /autoplay",
  "cyan nights • /lyrics",
  "mixing your mood • /queue",
  "mewbit.exe • /help",
  "nya-core online • /play",
  "cat ears, clean transitions",
  "purring in 320 kbps",
  "meow mixing your timeline",
  "one paw on the fader",
  "whiskers tuned to the bass",
  "mewtocol handshake complete",
  "bitrate with a side of nya",
  "mewbit is buffering feelings",
  "neon paws, illegal levels of groove",
  "cyber-cat radio never sleeps",
  "the catgirl has chosen the next song",
  "tail swishing at 140 BPM",
  "soft paws, hard bass",
  "pawsitive vibes only",
  "meowgic in the queue",
  "feline good about this mix",
  "certified meowster of ceremonies",
  "mewbit's secret catnip playlist",
  "headphones on, reality off",
  "your local neon music gremlin",
  "cute avatar, dangerous autoplay",
  "small cat, enormous soundstage",
  "the purrfect transition is loading",
  "nya nya, no skips today",

  // Anime / vocaloid / cyberpunk
  "senpai noticed the bassline",
  "opening theme energy unlocked",
  "ending credits but the party continues",
  "main character mix activated",
  "training arc: learning your taste",
  "power of friendship, powered by bass",
  "the filler episode has a banger",
  "anime protagonist at the aux",
  "not a filler track in sight",
  "shōnen jump straight into the chorus",
  "stand proud, the queue is cooking",
  "bankai: maximum volume responsibly",
  "domain expansion: dancefloor",
  "cursed energy, blessed playlist",
  "the strongest DJ of today",
  "gojo would skip this transition",
  "believe it: /autoplay is on",
  "rasengan of rhythm incoming",
  "the village hidden in the bass",
  "spirit bomb made of subwoofers",
  "plus ultra into the next song",
  "quirk: impossible to pick a bad track",
  "hero license: approved by the beat",
  "the moon prism approves this vibe",
  "sailor bass reporting for duty",
  "moonlight, neon, and suspiciously good drums",
  "miku-coded, mewbit-approved",
  "vocaloid vocals, catgirl control room",
  "hologram hair, analog feelings",
  "lost in the synthwave dimension",
  "the cyberpunk anime side character with aux",
  "night city radio, unofficial edition",
  "afterlife club playlist curator",
  "chrome heart, warm chorus",
  "edgerunner fuel: one more song",
  "the red moon has a playlist",
  "slice of life, served with bass",
  "isekai'd into your queue",
  "the soundtrack to your training montage",

  // Games
  "respawning the bassline",
  "quest objective: find a better song",
  "rare drop: a seamless transition",
  "legendary loot in the queue",
  "critical hit on the chorus",
  "boss music detected",
  "final boss: an empty queue",
  "speedrunning your playlist",
  "no-hit run through bad vibes",
  "XP gained: +100 rhythm",
  "the NPC has better taste than you",
  "press A to dance",
  "player two joined the aux",
  "loading screen, but make it musical",
  "save point reached • /queue",
  "side quest: make the room move",
  "inventory full of certified bangers",
  "combo meter: still rising",
  "perfect parry on the beat drop",
  "stealth mode: sneaking into your feelings",
  "night city calls, MewBit answers",
  "the V in vibe stands for volume",
  "no fast travel, only smooth transitions",
  "the Witcher would approve this contract",
  "dragonborn by day, DJ by night",
  "fus ro dah the boring song away",
  "the Tarnished found the dancefloor",
  "maidenless but never playlistless",
  "Persona 5 menu music energy",
  "take your heart, leave the aux",
  "social link increased: +1 banger",
  "Hades keeps sending me back to the queue",
  "one more run, one more track",
  "the farm is automated, the vibe is not",
  "Stardew Valley after dark",
  "creeper? aw man, play something louder",
  "redstone-powered rhythm section",
  "the villagers are judging your shuffle",
  "kart drift into the next chorus",
  "blue shell aimed at bad music",
  "the princess is in another playlist",
  "catching feelings and Pokémon",
  "Gotta queue 'em all",
  "the lobby heard the beat drop",
  "GG EZ, immaculate vibe",
  "skill issue: not using /autoplay",
  "touch grass? I chose touch the fader",
  "the loading bar is actually a synth pad",

  // Films / series / internet culture
  "the Matrix has you, MewBit has the queue",
  "red pill, blue pill, pink neon playlist",
  "may the bass be with you",
  "this is the way to the next track",
  "winter is coming, the beat already arrived",
  "one does not simply skip this chorus",
  "you shall not pass the aux",
  "the fellowship of the bass",
  "Wakanda forever, autoplay foreverer",
  "with great power comes great playlists",
  "friendly neighborhood beat dealer",
  "the multiverse has many remixes",
  "Stranger Things are happening to this bass",
  "the upside down has better acoustics",
  "breaking beats, not bad news",
  "this playlist is not a phase, mom",
  "the office has been replaced by the aux",
  "Dunder Mifflin branch: MewBit division",
  "shrek said it best: get out of my swamp, bad vibes",
  "ogre-sized bass, tiny catgirl manager",
  "John Wick of the beat drop",
  "no time to die, plenty of time to dance",
  "mission accepted: improve the atmosphere",
  "the force is strong with this transition",
  "plot twist: the next song is actually good",
  "season finale: the queue survives",
  "post-credit scene: another banger",
  "director's cut of your listening session",
  "critics say: surprisingly no skips",

  // Dev / terminal / MewBit lore
  "npm install dopamine",
  "npm run vibe",
  "git commit -m 'fixed the aux'",
  "merge conflict resolved with a bass drop",
  "404: boring music not found",
  "500: server is too busy vibing",
  "localhost:2333 is feeling musical",
  "Docker container full of tiny DJs",
  "production-ready-ish catgirl",
  "deploying vibes to production",
  "hotfixing your mood in real time",
  "pull request: approve this banger",
  "code review says: needs more bass",
  "stack trace points to the dancefloor",
  "undefined is not a vibe",
  "null pointer, non-null groove",
  "segmentation fault in the sad playlist",
  "while(true) { playNext(); }",
  "try { vibe(); } catch { dance(); }",
  "async function chooseBanger()",
  "awaiting the perfect transition",
  "promise resolved: the beat goes on",
  "garbage collector removed the cringe",
  "cache hit: your favorite chorus",
  "API response: immaculate",
  "rate limit reached on compliments",
  "logging your suspiciously good taste",
  "debug mode: listening closely",
  "verbose logs, louder bass",
  "feature branch: catgirl mode",
  "release candidate for the dancefloor",
  "semantic versioning, chaotic playlists",
  "linting the vibes",
  "tests passed, hips unlocked",
  "CI pipeline full of synths",
  "the bug was in the aux cable",
  "works on my headphones",
  "documented in the README of your heart",
  "powered by caffeine and questionable commits",
  "the dev is listening to the logs",
  "no framework can contain this groove",

  // Cringe / meme / chaotic variety
  "uwu what's this? a certified banger",
  "rawr xD welcome to the dancefloor",
  "nyaa, I accidentally made a good playlist",
  "bonk! bad vibes have been removed",
  "goofy ahh mix, immaculate results",
  "bro really queued another one",
  "bro is absolutely cooking",
  "the vibe is vibing",
  "no thoughts, head full of bass",
  "emotionally attached to this hi-hat",
  "caught in 4K enjoying the chorus",
  "based shuffle, no notes",
  "cringe is temporary, bangers are eternal",
  "certified yapper, professional listener",
  "main character syndrome detected",
  "plot armor protecting the queue",
  "NPC dialogue replaced with music",
  "side eyeing the skip button",
  "the skip button is on probation",
  "gaslight, gatekeep, girlboss the playlist",
  "girl dinner, cat dinner, bass dinner",
  "we are so back",
  "it is so over, play another one",
  "absolute cinema, questionable volume",
  "let him cook, he knows the next song",
  "chat, is this fire?",
  "chat chose violence and /autoplay",
  "the council has approved this track",
  "vibe check: passed with glitter",
  "sending this beat to the group chat",
  "your honor, the groove was irresistible",
  "I can explain the 17-hour queue",
  "one more song is a legally binding promise",
  "sleep is temporary, playlists are forever",
  "my cat walked on the keyboard and chose this",
  "no refunds for emotional damage from the drop",
  "the aux is a privilege, not a right",
  "please remain calm, the chorus is approaching",
  "this could have been an email, but it is a banger",
  "your daily dose of audio nonsense",
  "professionally unserious since startup",
  "too cute to buffer",
  "too loud to be ignored",
  "emotionally support playlist deployed",
  "the algorithm has entered its silly era",
  "shuffle with confidence, coward",
  "MewBit knows what you did last queue",
  "I am once again asking for /lyrics",
  "the beat drop has been peer reviewed",
  "no cap, all waveform",
];

const PERSONALIZED_PRESENCE_TEMPLATES = [
  (name) => `nya ${name} • your aux privileges are under review`,
  (name) => `${name}'s soundtrack is being upgraded`,
  (name) => `MewBit caught ${name} being the main character`,
  (name) => `${name} requested vibes, catgirl delivered`,
  (name) => `the council of cats has selected ${name}`,
  (name) => `${name} is legally required to enjoy this chorus`,
  (name) => `playlist diagnostics: ${name} needs more bass`,
  (name) => `${name} entered the neon timeline`,
  (name) => `MewBit.exe is simping for ${name}'s taste`,
  (name) => `${name} has been promoted to honorary DJ`,
  (name) => `warning: ${name} is approaching the aux`,
  (name) => `${name} rolled a natural 20 on vibe check`,
  (name) => `${name} unlocked the secret catgirl radio`,
  (name) => `the next banger is dedicated to ${name}`,
  (name) => `${name} vs. the skip button • final boss`,
  (name) => `${name} is in the queue lore now`,
  (name) => `MewBit asked ${name} to touch the fader`,
  (name) => `${name}'s NPC arc has a surprisingly good soundtrack`,
  (name) => `if lost, return ${name} to the dancefloor`,
  (name) => `${name} has been perceived by the algorithm`,
];

const BRAND = {
  name: "mewbit",
  tagline: "neon sounds for every mood",
  presence: PRESENCE_LINES,
  colors: {
    primary: "#19e6ff",
    secondary: "#ff2bd6",
    deep: "#17124f",
    success: "#22e6b8",
    warning: "#ffcc66",
    error: "#ff4f8b",
  },
};

function sanitizePresenceName(value) {
  return String(value || "")
    .replace(/@(?:everyone|here)/gi, "")
    .replace(/[\\`*_~|<>]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 32);
}

function getCachedMembers(client) {
  const members = new Map();

  for (const guild of client?.guilds?.cache?.values?.() || []) {
    for (const member of guild.members?.cache?.values?.() || []) {
      if (member.user?.bot) continue;

      const name = sanitizePresenceName(member.displayName || member.user?.globalName || member.user?.username);
      if (name) members.set(member.id || member.user?.id || name, name);
    }
  }

  return [...members.values()];
}

function getPresenceLines(client, offset = 0) {
  const names = getCachedMembers(client);
  if (names.length === 0) return [...BRAND.presence];

  const name = names[Math.abs(offset) % names.length];
  const personalized = PERSONALIZED_PRESENCE_TEMPLATES.map((template) => template(name));
  return [...BRAND.presence, ...personalized];
}

function brandFooter(section) {
  return section ? `${BRAND.name} • ${section}` : BRAND.name;
}

module.exports = {
  BRAND,
  PERSONALIZED_PRESENCE_TEMPLATES,
  PRESENCE_LINES,
  brandFooter,
  getPresenceLines,
  sanitizePresenceName,
};
