services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: neo-lavalink
    env_file:
      - .env
    environment:
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: ${LAVALINK_PASSWORD:-youshallnotpass}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID:-}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET:-}
      YOUTUBE_PO_TOKEN: ${YOUTUBE_PO_TOKEN:-}
      YOUTUBE_VISITOR_DATA: ${YOUTUBE_VISITOR_DATA:-}
      YOUTUBE_REFRESH_TOKEN: ${YOUTUBE_REFRESH_TOKEN:-}
      DEEZER_ARL_TOKEN: ${DEEZER_ARL_TOKEN:-}
      DEEZER_MASTER_KEY: ${DEEZER_MASTER_KEY:-}
    volumes:
      - ./helpers/lavalink/application.yml:/opt/Lavalink/application.yml:ro
      - ./helpers/lavalink/plugins:/opt/Lavalink/plugins
      - ./helpers/lavalink/youtube-cookies.txt:/opt/Lavalink/youtube-cookies.txt:ro
    ports:
      - "2333:2333"
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'curl -sf -H "Authorization: ${LAVALINK_SERVER_PASSWORD:-youshallnotpass}" http://localhost:2333/version || exit 1'
      interval: 15s
      timeout: 5s
      retries: 5

  bot:
    image: marczelloo/neo-beat-buddy:latest
    depends_on:
      lavalink:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - ./helpers/data:/app/helpers/data # Persist data across restarts
      - ./logs:/app/logs
    restart: unless-stopped
